# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gcontent',
            field=models.CharField(max_length=200),
        ),
    ]
